from enum import Enum


class BasicConfig(Enum):
    SHINGLE_VAlUE = 5
    JACCARD_THRESHOLD = 0.72
    MAX_BATCH_ITEM_QUANTITY = 20
    BATCH_TOKEN_THRESHOLD = 8000
    SEMAPHORE_VALUE = 10
    LLM_INPUT_COST_PER_1K = 0.0025
    LLM_OUTPUT_COST_PER_1K = 0.01